DROP TABLE IF EXISTS {$DBPREFIX$}{$PACKAGENAME$}_{$MODULENAME$}_profiles;
DROP TABLE IF EXISTS {$DBPREFIX$}{$PACKAGENAME$}_{$MODULENAME$}_groups;
DROP TABLE IF EXISTS {$DBPREFIX$}{$PACKAGENAME$}_{$MODULENAME$}_tasks;
DROP TABLE IF EXISTS {$DBPREFIX$}{$PACKAGENAME$}_{$MODULENAME$}_tasks_images;
DROP TABLE IF EXISTS {$DBPREFIX$}{$PACKAGENAME$}_{$MODULENAME$}_tasks_documents;
DROP TABLE IF EXISTS {$DBPREFIX$}{$PACKAGENAME$}_{$MODULENAME$}_uploads;
DROP TABLE IF EXISTS {$DBPREFIX$}{$PACKAGENAME$}_{$MODULENAME$}_posts;